import time
from ..utils.badges import generate_badge_url
from urllib.parse import urlencode


class Other:
    def __init__(self, config):
        self.config = config
        self.technology_stacks = Other.__generate_technology_stacks(
            config["technology-stacks"]
        )
        self.readme_typing = Other.__generate_readme_typing(config["readme-typing"])
        self.generate_time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        self.copyright = """
<!--
WARNING: This is a generated file. Do not edit this file directly.
COPYRIGHT: Shevon Kuan
    Thank you if you like this profile README!

    BUT, please DO NOT copy this and create your profile based on it.

    It is very common that you forget to change some information and leave
    mine in your profile. This has happened too many times.

    If you want to create a profile README like this, please use the 
    github_readme_generator module in this repo and use
    `python -m github_readme_generator -c content/content.yaml -t README_template.md -o readme.md` to generate your own README.
    
    Remember to change the content in `content/content.yaml` to your own information.
    
    Wish you a good-looking profile README!

                                   —— ShevonKuan (https://github.com/ShevonKuan)

-->
        
        """
    @staticmethod
    def __generate_technology_stacks(c):
        badges = c["badges"]
        output = ""
        theme_color = c.get("theme-color", "000")
        style = c.get("style", "flat")
        theme = c.get("theme", "unify")
        for section in badges:
            output += "> ##### " + section["title"] + "\n> "
            badge_urls = generate_badge_url(section["badge"], theme, theme_color, style)
            for url in badge_urls:
                output += url + " "
            output += "\n" * 2
        return output

    @staticmethod
    def __generate_readme_typing(c):
        return f'![](https://readme-typing-svg.herokuapp.com?{urlencode(c)})'
